version: 2

sources:

  - name: local_bike
    schema: LocalBike
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: orders
      - name: order_items
      - name: products
      - name: staffs
      - name: stocks
      - name: stores